import GlobalState from '@/context'
import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Notification from '@/components/Notification'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='h-full bg-gray-900'>
      <body className={inter.className+' h-full'}>
        
          <GlobalState>
            <Navbar>
              <main className='flex flex-col '>{children}</main>
            </Navbar>
             <Notification />
          </GlobalState>
      </body>
    </html>
  )
}
